# Generated by Django 3.2.25 on 2024-11-18 23:46

from django.db import migrations, models
import mt.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0002_auto_20241116_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image1', models.ImageField(blank=True, upload_to='post_pics')),
                ('image2', models.ImageField(blank=True, upload_to='post_pics')),
                ('image3', models.ImageField(blank=True, upload_to='post_pics')),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': 'This username is already taken.'}, max_length=20, null=True, unique=True, validators=[mt.validators.validate_no_special_characters]),
        ),
    ]
